// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7XqZ8GDktrJwDBZHhwAUEbmB8XbKNOkE',
    appId: '1:190089077264:web:732a70b05c3afc84ca6095',
    messagingSenderId: '190089077264',
    projectId: 'jpp-driver',
    authDomain: 'jpp-driver.firebaseapp.com',
    storageBucket: 'jpp-driver.appspot.com',
    measurementId: 'G-YMS61CNKFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKu7RjhdsxDAx0cl306Qa22XdqR6kA0rE',
    appId: '1:190089077264:android:b5d58ccf97dad4faca6095',
    messagingSenderId: '190089077264',
    projectId: 'jpp-driver',
    storageBucket: 'jpp-driver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-OhlSKKjXrM_zlDG9lzPnByKLO1So6jc',
    appId: '1:190089077264:ios:3ba48486bc5954c0ca6095',
    messagingSenderId: '190089077264',
    projectId: 'jpp-driver',
    storageBucket: 'jpp-driver.appspot.com',
    iosBundleId: 'com.byteplace.gigly.driver.ride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-OhlSKKjXrM_zlDG9lzPnByKLO1So6jc',
    appId: '1:190089077264:ios:9b0a4a70c12f9a72ca6095',
    messagingSenderId: '190089077264',
    projectId: 'jpp-driver',
    storageBucket: 'jpp-driver.appspot.com',
    iosBundleId: 'com.example.silkrouteFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7XqZ8GDktrJwDBZHhwAUEbmB8XbKNOkE',
    appId: '1:190089077264:web:6fc8cc9892a4d3f7ca6095',
    messagingSenderId: '190089077264',
    projectId: 'jpp-driver',
    authDomain: 'jpp-driver.firebaseapp.com',
    storageBucket: 'jpp-driver.appspot.com',
    measurementId: 'G-JPEFXQ3KVY',
  );
}
