// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class FirebaseOptionsGiglyaiDriver {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbE0YM_f0-VRvJl7-SUfyl9dYMQ2mbncg',
    appId: '1:1036080645950:web:a04f663a6de6f3798d8e6f',
    messagingSenderId: '1036080645950',
    projectId: 'ai-gigly-driver-ride',
    authDomain: 'ai-gigly-driver-ride.firebaseapp.com',
    storageBucket: 'ai-gigly-driver-ride.appspot.com',
    measurementId: 'G-EWF1NM2ZTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuE1CMb91zyXT53W2m8HjCsQk4xhvzmkg',
    appId: '1:1036080645950:android:04b4eeca9a3b03cd8d8e6f',
    messagingSenderId: '1036080645950',
    projectId: 'ai-gigly-driver-ride',
    storageBucket: 'ai-gigly-driver-ride.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlRv7XIt3DY0oZvXYoHkSEKUd1zxB6pj8',
    appId: '1:1036080645950:ios:449e31f9397bd5e78d8e6f',
    messagingSenderId: '1036080645950',
    projectId: 'ai-gigly-driver-ride',
    storageBucket: 'ai-gigly-driver-ride.appspot.com',
    iosBundleId: 'com.byteplace.gigly.driver.ride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlRv7XIt3DY0oZvXYoHkSEKUd1zxB6pj8',
    appId: '1:1036080645950:ios:7b163ad2ab2289848d8e6f',
    messagingSenderId: '1036080645950',
    projectId: 'ai-gigly-driver-ride',
    storageBucket: 'ai-gigly-driver-ride.appspot.com',
    iosBundleId: 'com.example.silkrouteFlutter',
  );
}
