// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class PrithviDriverFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACVSccm_Rbn82pIt95jDvBgfrpCRT9-TY',
    appId: '1:1051902992975:web:e59488ae7fea064ddfc03a',
    messagingSenderId: '1051902992975',
    projectId: 'prithvi-driver',
    authDomain: 'prithvi-driver.firebaseapp.com',
    storageBucket: 'prithvi-driver.appspot.com',
    measurementId: 'G-PJQBFFEJ5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTqKQMfsovSIT0_wHMAIOGPyyDB2pJlDo',
    appId: '1:1051902992975:android:7505a130873f1c74dfc03a',
    messagingSenderId: '1051902992975',
    projectId: 'prithvi-driver',
    storageBucket: 'prithvi-driver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMfQ1GFT76NmBuUt0sqiez0y3_3SXF6Cc',
    appId: '1:1051902992975:ios:28aca52a72fd686adfc03a',
    messagingSenderId: '1051902992975',
    projectId: 'prithvi-driver',
    storageBucket: 'prithvi-driver.appspot.com',
    iosBundleId: 'com.byteplace.gigly.driver.ride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMfQ1GFT76NmBuUt0sqiez0y3_3SXF6Cc',
    appId: '1:1051902992975:ios:25616d440bc6fab8dfc03a',
    messagingSenderId: '1051902992975',
    projectId: 'prithvi-driver',
    storageBucket: 'prithvi-driver.appspot.com',
    iosBundleId: 'com.example.silkrouteFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACVSccm_Rbn82pIt95jDvBgfrpCRT9-TY',
    appId: '1:1051902992975:web:eca67e667853c64adfc03a',
    messagingSenderId: '1051902992975',
    projectId: 'prithvi-driver',
    authDomain: 'prithvi-driver.firebaseapp.com',
    storageBucket: 'prithvi-driver.appspot.com',
    measurementId: 'G-W31ZY82X49',
  );
}
