// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class OorugoDriverFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx_H01Ulrlt1YkWI5l8prwsgrMyp86__g',
    appId: '1:994713223903:web:a6863e9467137ffa2adf6a',
    messagingSenderId: '994713223903',
    projectId: 'oorugo-driver',
    authDomain: 'oorugo-driver.firebaseapp.com',
    storageBucket: 'oorugo-driver.appspot.com',
    measurementId: 'G-BGL3BRZ37Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPalhgnRkzRq_9UKbVtA9Nhzh_KK_Ie7w',
    appId: '1:994713223903:android:594d2d4656f399ff2adf6a',
    messagingSenderId: '994713223903',
    projectId: 'oorugo-driver',
    storageBucket: 'oorugo-driver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcVxuBTM9gZa3aUIY-llhJDbfTBe_i4g8',
    appId: '1:994713223903:ios:95f9d6868ac079742adf6a',
    messagingSenderId: '994713223903',
    projectId: 'oorugo-driver',
    storageBucket: 'oorugo-driver.appspot.com',
    iosBundleId: 'com.byteplace.gigly.driver.ride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcVxuBTM9gZa3aUIY-llhJDbfTBe_i4g8',
    appId: '1:994713223903:ios:e1758a3d8280c2062adf6a',
    messagingSenderId: '994713223903',
    projectId: 'oorugo-driver',
    storageBucket: 'oorugo-driver.appspot.com',
    iosBundleId: 'com.example.silkrouteFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx_H01Ulrlt1YkWI5l8prwsgrMyp86__g',
    appId: '1:994713223903:web:d9e7b72bb2550ede2adf6a',
    messagingSenderId: '994713223903',
    projectId: 'oorugo-driver',
    authDomain: 'oorugo-driver.firebaseapp.com',
    storageBucket: 'oorugo-driver.appspot.com',
    measurementId: 'G-0FHY10R6GS',
  );
}
