const Map<String, dynamic> defaultValues = <String, dynamic>{
  "isInventoryTabAvailable": true,
};

const Map<String, dynamic> defaultLocalizationData = {
  "en_US": {
    "profile": "Profile",
    "document": "Documents",
    "vehicle": "Vehicle",
    "my_agency": "My Agency",
    "offers": "Offers",
    "earnings": "Earnings",
    "trips": "Trips",
    "wallet": "Wallet",
    "notification": "Notification",
    "logout": "Logout",
    "terms_condition": "Terms & Condition",
    "help": "Help",
    "privacy_policy": "Privacy Policy",
    "choose_language": "Choose Language",
    "rides": "Rides",
    "Ads_manager": "Ads Manager",
    "name_address": "Name Address",
    "name": "Name",
    "address": "Address",
    "enter_your_name": "Enter Your Name",
    "continue": "Continue",
    "vehicle_details": "Vehicle Details",
    "add_your_vehicle_details": "Add your vehicle details",
    "vehicle_category": "Vehicle Category",
    "select_category": "Select Category",
    "vehicle_model": "Vehicle Model",
    "select_model": "Select Model",
    "vehicle_number": "Vehicle Number",
    "enter_vehicle_number_here": "Enter vehicle number here",
    "drivers_license": "Drivers license",
    "enter_drivers_license_number_here": "Drivers license",
    "vehicle_type": "Vehicle Name",
    "save": "Save",
    "online": "Online",
    "offline": "Offline",
    "search": "Search Rides",
    "upcoming_rides": "Upcoming Rides",
    "pickup_time": "Pickup time",
    "start_now": "Start Now",
    "Do_you_want_to_cancel_this_ride": "Do you want to cancel this\nride",
    "No_ride_available_moment_please_try_requesting_later":
        "No ride available at this moment. Please try \nrequesting later",
    "ok": "Ok",
    "how_are_you_travelling_to_user_location?":
        "How are you travelling to user location?",
    "leads": "Leads",
    "bookings": "Bookings",
    "ratings": "Ratings",
    "offers_partner": "Offers",
    "business_overview": "Business Overview",
    "total_view_of_your_business":
        "Total view of your business across all your outlest",
    "Your_account_is_not_verified": "Your account is not verified",
    "complete_your_profile": "Complete your profile",
    "upload_the_following_documents": "Upload the following documents",
    "your_account_is_under_verification": "Your account is under verification",
    "This_might_take_upto_24_hours": "This might take upto 24 hours",
    "chat_with_help_team": "Chat with help team",
    "partner_document": "Partner Document",
    "select_document_from_gallery": "Select document from gallery",
    "upload_documents": "Upload documents",
    "upload_front_side_image_of_your_documents":
        "Upload front side image of your\n Documents",
    "upload_back_side_image_of_your_documents":
        "Upload back side image of your\n Documents",
    "documents_submitted": "Documents Submitted ",
    "verification_is_under_process": "Verification is under process",
    "your_account_is_verified": "Your account is verified",
    "edit_account": "Edit Account",
    "seller_name": "Seller Name",
    "business_name": "Business Name",
    "first_name": "First Name",
    "last_name": "Last Name",
    "phone_number": "Phone Number",
    "email": "Email",
    "enter_valid_email": "Enter Valid Email",
    "account_deletion": "Account deletion",
    "Choose_from_library": "Choose from library",
    "take_photo": "Take Photo",
    "confirm": "Confirm",
    "cancel": "Cancel",
    "confirm_deletion": "Confirm Deletion!",
    "are_you_sure_you_want_to_delete_this_account_permamnently_you_can":
        "Are you sure you want to Delete this account permamnently! You can ",
    "my_agencies": "My Agencies",
    "ad_balance": "Ad Balance",
    "ads": "Ads",
    "you_need_minimum_ad": "You need minimum INR 1000 on you wallet, to run ad",
    "ad": "Ad",
    "go_to_ads_insights": "Go to Ads Insights",
    "all_transactions": "All transactions",
    "to_see_your_ad": "To see your ad performance, go to ads insights",
    "add_money": "Add Money",
    "create_ad": "Create Ad",
    "ad_location": "Ad Location",
    "enter_location": "Enter location",
    "enter_cost_per_click": "Enter Cost per Click",
    "update_ad": "Update Ad",
    "ads_insights": "Ads Insights",
    "see_how_your_sales":
        "See how your website is performing in Ads to \nincrease sales",
    "active": "Active",
    "completed": "Completed",
    "no_data_available": "No data available",
    "earning_activity": "Earning Activity",
    "total_earnings": "Total Earnings",
    "breakdown": "Breakdown",
    "total_trips": "Total Trips",
    "total_distance": "Total Distance",
    "total_time": "Total Time",
    "payment_received_for_completed_trip":
        "Payment Received for Completing \nthe Trip",
    "trip": "Trips",
    "complete": "completed",
    "cancelled": "Cancelled",
    "assigned": "Assigned",
    "completed_trips": "Completed Trips",
    "breakdown_trips": "Breakdown",
    "total_distance_trips": "Total Distance",
    "total_time_trips": "Total Time",
    "assigned_trips": "Assigned Trips",
    "wallets": "Wallet",
    "ads_transaction": "Ads Transactions",
    "no_transaction": "No Transactions",
    "balance": "Balance",
    "cash_out_balance": "Cash Out Balance",
    "no_data": "No Data",
    "cashout_method": "Cashout Method",
    "bank_account": "Bank account ****** 3654",
    "instant_cash_subtotal": "Instant cash subtotal",
    "processing_fee": "Processing fee",
    "Cash_out_transfer_total": "Cash Out Transfer Total",
    "this_transferred":
        "This is the amount that will be transferred to \nyour bank account when you tap “Cashout”.",
    "enter_amount": "Enter amount",
    "you_can_also_select_amount": "You can also select amount",
    "minimum_amount_100": "(Minimum Amount: INR 100)",
    "inr": "INR",
    "your_balance": "Your balance",
    "notifications": "Notifications",
    "recent": "recent",
    "all": "All",
    "read": "Read",
    "new": "New",
    "ratings_reviews": "Rating and Reviews",
    "what_customers_say_about_us": "What customers say about us",
    "check_the_feedbacks_products":
        "Check the feedbacks you’ve got on your \nproducts",
    "filter_reviews": "Filter Reviews",
    "see_all_reviews": "See all reviews",
    "create_offer": "Create Offer",
    "enter_offer_name": "Enter Offer Name",
    "offer_name": "Offer Name",
    "offer_percentage": "Offer Percentage",
    "select_enter_the_offer_percentage": "Select / enter the  offer percentage",
    "select_your_language": "Select your language",
    "you_can_change_your_language_on_this_screen_anytime":
        "you can change your language on this \nscreen anytime",
    "language": "Language",
    "choose_language_op": "Choose Language",
    "hindi": "Hindi",
    "english": "English"
  }
};

List<String> defaultNotificationTopics = ["news"];
